version: '3'
services:
  nuxt-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-ssr
    ports:
      - "4000:3000"
    networks:
      - frontend-net
    restart: unless-stopped

networks:
  frontend-net:
    external: true
